#!/usr/bin/env bash

set -Eeuo pipefail

if [[ "$#" == 1 && "$1" == "--version" ]]; then
    printf '2.6.1\n'
    exit 0
fi

printf 'developer_dir=%s maestro %s\n' "${DEVELOPER_DIR:?}" "$*" >>"${STUB_OPERATION_LOG:?}"

report_file=""
artifact_dir=""
debug_dir=""
while (( $# > 0 )); do
    case "$1" in
        --output)
            report_file="$2"
            shift 2
            ;;
        --test-output-dir)
            artifact_dir="$2"
            shift 2
            ;;
        --debug-output)
            debug_dir="$2"
            shift 2
            ;;
        *) shift ;;
    esac
done

[[ -n "$report_file" && -n "$artifact_dir" && -n "$debug_dir" ]] || exit 2
printf '<testsuite tests="1" failures="0"><testcase status="SUCCESS"/></testsuite>\n' >"$report_file"
printf 'debug log\n' >"$debug_dir/maestro.log"
printf '{}\n' >"$debug_dir/commands-(reference-screens).json"
printf 'png\n' >"$artifact_dir/screenshots/01.png"
printf 'png\n' >"$artifact_dir/screenshots/02.png"
printf 'png\n' >"$artifact_dir/screenshots/03.png"
